
PASSENGER_ID = 9
PASSENGER_EMAIL = ''
PASSENGER_PASSWORD = ''

DRIVER_ID = 1
DRIVER_EMAIL = ''
DRIVER_PASSWORD = ''

ADMIN_ID = 2
ADMIN_EMAIL = ''
ADMIN_PASSWORD = ''

ACCOUNT_ACTIVATION_ID = 1
ACCOUNT_ACTIVATION_ID_EXPIRED = 654321
ACCOUNT_ACTIVATION_ID_NON_EXISTING = 123321

PASSWORD_RESET_CODE = 123456
PASSWORD_RESET_CODE_EXPIRED = 123321
PASSWORD_RESET_USER_ID_EXPIRED = 6

RIDE_ID_FOR_MESSAGES = 1

PASSENGER_ATTACHED_TO_RIDE_ID = 8
PASSENGER_ATTACHED_TO_RIDE_EMAIL = ''

ASSIGNED_DRIVER_PASSWORD = ""
